name: Check RSS & Atom feeds

on:
  schedule:
    # every day at 04:17 PT
    - cron: 17 4 * * *
      timezone: America/Los_Angeles
  workflow_dispatch:

permissions:
  contents: write

env:
  BRANCH_NAME: rss_test_branch_3

jobs:
  run-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        id: branch-check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh api repos/${{ github.repository }}/branches/${{ env.BRANCH_NAME }} -X HEAD
          then
            echo "exists=yes" >> "$GITHUB_OUTPUT"
          else
            echo "exists=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ case(steps.branch-check.outputs.exists == 'yes', env.BRANCH_NAME, 'main') }}

      - name: Set up git author
        run: git config user.name joe

      - name: Set up branch
        if: ${{ steps.branch-check.outputs.exists == 'no' }}
        run: |
          # checkout stages main's files, and switch doesn't
          git switch --orphan ${{ env.BRANCH_NAME }}
          touch urls
          git add urls
          git commit -m "set up rss branch"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2

      - name: Build ringfairy
        run: cargo build --release

      - name: Check RSS feeds
        id: rss
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          URLS_OLD=$(cat urls)
          if ./target/release/rss "$URLS_OLD" >> urls
          then
            echo "new-posts=yes" >> "$GITHUB_OUTPUT"
          else
            echo "new-posts=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Save URLs
        if: ${{ steps.rss.outputs.new-posts == 'yes' }}
        run: |
          git add urls
          git commit -m "new blocks"
          git push origin ${{ env.BRANCH_NAME }}
